[features]
seeds = false
skip-lint = false
[programs.localnet]
solswipe = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/alicehume/.config/solana/id.json"

[scripts]
test = "node tests/solswipe.js"
